import type { CuratedBiblicalEntry } from "./curated-types";

function entry(
  partial: Omit<CuratedBiblicalEntry, "formattedReference" | "verseEnd"> & {
    verseEnd?: number;
  },
): CuratedBiblicalEntry {
  const verseEnd = partial.verseEnd ?? partial.verseStart;
  const formattedReference =
    verseEnd !== partial.verseStart
      ? `${partial.book} ${partial.chapter}:${partial.verseStart}-${verseEnd}`
      : `${partial.book} ${partial.chapter}:${partial.verseStart}`;
  return {
    ...partial,
    verseEnd,
    formattedReference,
  };
}

/**
 * Curated editorial corpus v1 — references + paraphrases only.
 * No full text from modern licensed Bible translations.
 */
export const CURATED_BIBLICAL_CORPUS_V1: CuratedBiblicalEntry[] = [
  entry({
    id: "mt-6-25-34",
    book: "Mateus",
    chapter: 6,
    verseStart: 25,
    verseEnd: 34,
    testament: "nt",
    themes: ["ansiedade", "dinheiro", "fe", "oracao"],
    editorialSummary:
      "Em síntese, o ensino convida a não se consumir pela preocupação com o amanhã, confiando no cuidado do Pai e buscando primeiro o Reino.",
    contextNote:
      "Sermão do Monte: contraste entre ansiedade cotidiana e confiança confessional.",
    isGospel: true,
  }),
  entry({
    id: "mt-11-28-30",
    book: "Mateus",
    chapter: 11,
    verseStart: 28,
    verseEnd: 30,
    testament: "nt",
    themes: ["ansiedade", "sofrimento", "recomeco", "fe"],
    editorialSummary:
      "A passagem ensina o convite a trazer o cansaço a Cristo, encontrando descanso no jugo suave do discipulado.",
    contextNote: "Convite pessoal de Jesus a quem está sobrecarregado.",
    isGospel: true,
  }),
  entry({
    id: "fp-4-6-7",
    book: "Filipenses",
    chapter: 4,
    verseStart: 6,
    verseEnd: 7,
    testament: "nt",
    themes: ["ansiedade", "oracao", "fe", "gratidao"],
    editorialSummary:
      "Em síntese, Paulo orienta a substituir a ansiedade pela oração com ação de graças, recebendo a paz de Deus que guarda o coração.",
    contextNote: "Exortação pastoral ao final da carta aos filipenses.",
    isPauline: true,
    denominationalNotes:
      "Tradições convergem no valor da oração; diferenças aparecem mais no modo de contemplação e liturgia.",
  }),
  entry({
    id: "1pe-5-7",
    book: "1 Pedro",
    chapter: 5,
    verseStart: 7,
    testament: "nt",
    themes: ["ansiedade", "fe", "oracao"],
    editorialSummary:
      "A passagem ensina a lançar sobre Deus toda ansiedade, porque Ele cuida.",
    contextNote: "Contexto de humildade e vigilância sob pressão.",
  }),
  entry({
    id: "sl-27-1",
    book: "Salmos",
    chapter: 27,
    verseStart: 1,
    testament: "ot",
    themes: ["medo", "fe", "esperanca"],
    editorialSummary:
      "Em síntese, o salmista confessa o Senhor como luz e salvação, motivo para não temer.",
    contextNote: "Confissão de confiança diante de ameaças.",
  }),
  entry({
    id: "sl-23-1-4",
    book: "Salmos",
    chapter: 23,
    verseStart: 1,
    verseEnd: 4,
    testament: "ot",
    themes: ["medo", "luto", "esperanca", "solidao", "sofrimento"],
    editorialSummary:
      "À luz desse texto, o Senhor é pastor que sustenta mesmo no vale da sombra, sem abandonar o fiel.",
    contextNote: "Imagem pastoral clássica de cuidado e presença.",
  }),
  entry({
    id: "is-41-10",
    book: "Isaías",
    chapter: 41,
    verseStart: 10,
    testament: "ot",
    themes: ["medo", "esperanca", "fe", "perseveranca"],
    editorialSummary:
      "A passagem ensina que o povo não precisa temer, porque Deus fortalece e sustenta com a sua justa mão.",
    contextNote: "Oráculo de consolo ao povo em angústia nacional.",
  }),
  entry({
    id: "2tm-1-7",
    book: "2 Timóteo",
    chapter: 1,
    verseStart: 7,
    testament: "nt",
    themes: ["medo", "fe", "servico"],
    editorialSummary:
      "Em síntese, o Espírito dado por Deus não é de covardia, mas de poder, amor e domínio próprio.",
    contextNote: "Exortação a Timóteo diante de pressão e timidez.",
    isPauline: true,
  }),
  entry({
    id: "js-1-9",
    book: "Josué",
    chapter: 1,
    verseStart: 9,
    testament: "ot",
    themes: ["medo", "mudanca", "recomeco", "fe"],
    editorialSummary:
      "A passagem ensina a coragem na transição: ser forte porque o Senhor acompanha aonde for.",
    contextNote: "Comissionamento de Josué após a morte de Moisés.",
  }),
  entry({
    id: "ec-3-1-8",
    book: "Eclesiastes",
    chapter: 3,
    verseStart: 1,
    verseEnd: 8,
    testament: "ot",
    themes: ["mudanca", "luto", "decisoes", "proposito"],
    editorialSummary:
      "Em síntese, há tempo para cada estação da vida, incluindo chorar e rir, plantar e colher.",
    contextNote: "Poema sapiencial sobre ritmos e limites humanos.",
  }),
  entry({
    id: "2co-5-17",
    book: "2 Coríntios",
    chapter: 5,
    verseStart: 17,
    testament: "nt",
    themes: ["mudanca", "recomeco", "fe", "proposito"],
    editorialSummary:
      "À luz desse texto, em Cristo a pessoa se torna nova criatura: o antigo passa e o novo surge.",
    contextNote: "Ministério da reconciliação e identidade em Cristo.",
    isPauline: true,
  }),
  entry({
    id: "is-43-18-19",
    book: "Isaías",
    chapter: 43,
    verseStart: 18,
    verseEnd: 19,
    testament: "ot",
    themes: ["mudanca", "recomeco", "esperanca"],
    editorialSummary:
      "A passagem ensina a não se prender só ao passado, pois Deus anuncia um caminho novo no deserto.",
    contextNote: "Promessa de restauração após o exílio.",
  }),
  entry({
    id: "sl-34-18",
    book: "Salmos",
    chapter: 34,
    verseStart: 18,
    testament: "ot",
    themes: ["luto", "sofrimento", "esperanca", "ansiedade"],
    editorialSummary:
      "Em síntese, o Senhor está perto dos que têm o coração quebrantado e salva os abatidos de espírito.",
    contextNote: "Salmo de ação de graças após livramento.",
  }),
  entry({
    id: "mt-5-4",
    book: "Mateus",
    chapter: 5,
    verseStart: 4,
    testament: "nt",
    themes: ["luto", "esperanca", "sofrimento"],
    editorialSummary:
      "A passagem ensina a bem-aventurança dos que choram: serão consolados.",
    contextNote: "Bem-aventuranças no Sermão do Monte.",
    isGospel: true,
  }),
  entry({
    id: "jo-11-25-26",
    book: "João",
    chapter: 11,
    verseStart: 25,
    verseEnd: 26,
    testament: "nt",
    themes: ["luto", "esperanca", "fe", "sofrimento"],
    editorialSummary:
      "À luz desse texto, Jesus se apresenta como a ressurreição e a vida: quem crê vive, ainda que morra.",
    contextNote: "Diálogo com Marta antes da ressurreição de Lázaro.",
    isGospel: true,
    denominationalNotes:
      "A esperança escatológica é comum; liturgias de luto variam entre denominações.",
  }),
  entry({
    id: "rm-15-13",
    book: "Romanos",
    chapter: 15,
    verseStart: 13,
    testament: "nt",
    themes: ["esperanca", "fe", "oracao", "gratidao"],
    editorialSummary:
      "Em síntese, Deus é fonte de esperança, enchendo de alegria e paz os que crêem pelo Espírito.",
    contextNote: "Bênção pastoral no fechamento de uma seção de Romanos.",
    isPauline: true,
  }),
  entry({
    id: "hb-11-1",
    book: "Hebreus",
    chapter: 11,
    verseStart: 1,
    testament: "nt",
    themes: ["fe", "esperanca", "perseveranca"],
    editorialSummary:
      "A passagem ensina a fé como certeza daquilo que se espera e convicção do que não se vê.",
    contextNote: "Abertura do capítulo da fé com exemplos de perseverança.",
  }),
  entry({
    id: "lm-3-22-23",
    book: "Lamentações",
    chapter: 3,
    verseStart: 22,
    verseEnd: 23,
    testament: "ot",
    themes: ["esperanca", "recomeco", "sofrimento", "gratidao"],
    editorialSummary:
      "Em síntese, as misericórdias do Senhor se renovam cada manhã; sua fidelidade é grande.",
    contextNote: "Lamento que vira confiança no meio da devastação de Jerusalém.",
  }),
  entry({
    id: "mt-6-14-15",
    book: "Mateus",
    chapter: 6,
    verseStart: 14,
    verseEnd: 15,
    testament: "nt",
    themes: ["perdao", "relacionamentos", "conflitos", "oracao"],
    editorialSummary:
      "A passagem ensina a ligação entre perdoar o próximo e receber perdão do Pai.",
    contextNote: "Comentário após o Pai-Nosso no Sermão do Monte.",
    isGospel: true,
  }),
  entry({
    id: "mt-18-21-22",
    book: "Mateus",
    chapter: 18,
    verseStart: 21,
    verseEnd: 22,
    testament: "nt",
    themes: ["perdao", "relacionamentos", "conflitos", "raiva"],
    editorialSummary:
      "À luz desse texto, o perdão não se mede por um número limitado: deve ser generoso e reiterado.",
    contextNote: "Diálogo de Pedro com Jesus sobre quantas vezes perdoar.",
    isGospel: true,
  }),
  entry({
    id: "ef-4-31-32",
    book: "Efésios",
    chapter: 4,
    verseStart: 31,
    verseEnd: 32,
    testament: "nt",
    themes: ["perdao", "raiva", "relacionamentos", "conflitos"],
    editorialSummary:
      "Em síntese, Paulo chama a abandonar amargura e raiva, sendo bondosos e perdoando-se mutuamente como Deus perdoou.",
    contextNote: "Ética da nova humanidade em Cristo na carta aos efésios.",
    isPauline: true,
  }),
  entry({
    id: "cl-3-13",
    book: "Colossenses",
    chapter: 3,
    verseStart: 13,
    testament: "nt",
    themes: ["perdao", "relacionamentos", "familia", "conflitos"],
    editorialSummary:
      "A passagem ensina suporte e perdão mútuos, como o Senhor perdoou.",
    contextNote: "Virtudes da comunidade cristã renovada.",
    isPauline: true,
  }),
  entry({
    id: "1jo-1-9",
    book: "1 João",
    chapter: 1,
    verseStart: 9,
    testament: "nt",
    themes: ["culpa", "perdao", "recomeco", "fe"],
    editorialSummary:
      "Em síntese, se confessarmos os pecados, Deus é fiel e justo para perdoar e purificar.",
    contextNote: "Pastoral sobre comunhão, pecado e confissão.",
  }),
  entry({
    id: "sl-51-10-12",
    book: "Salmos",
    chapter: 51,
    verseStart: 10,
    verseEnd: 12,
    testament: "ot",
    themes: ["culpa", "perdao", "recomeco", "oracao"],
    editorialSummary:
      "À luz desse texto, o orante pede coração puro, espírito renovado e a alegria da salvação.",
    contextNote: "Salmo de arrependimento tradicionalmente ligado a Davi.",
  }),
  entry({
    id: "rm-8-1",
    book: "Romanos",
    chapter: 8,
    verseStart: 1,
    testament: "nt",
    themes: ["culpa", "perdao", "fe", "esperanca"],
    editorialSummary:
      "A passagem ensina que não há condenação para os que estão em Cristo Jesus.",
    contextNote: "Clímax da discussão sobre lei, pecado e Espírito.",
    isPauline: true,
  }),
  entry({
    id: "tg-1-19-20",
    book: "Tiago",
    chapter: 1,
    verseStart: 19,
    verseEnd: 20,
    testament: "nt",
    themes: ["raiva", "conflitos", "relacionamentos"],
    editorialSummary:
      "Em síntese, ser pronto para ouvir, tardio para falar e tardio para se irar: a ira humana não produz a justiça de Deus.",
    contextNote: "Ética prática da comunidade de Tiago.",
  }),
  entry({
    id: "pv-15-1",
    book: "Provérbios",
    chapter: 15,
    verseStart: 1,
    testament: "ot",
    themes: ["raiva", "conflitos", "relacionamentos"],
    editorialSummary:
      "A passagem ensina que a resposta branda desvia o furor, enquanto a palavra dura acende a ira.",
    contextNote: "Sabedoria sobre discurso e convivência.",
  }),
  entry({
    id: "ef-6-1-4",
    book: "Efésios",
    chapter: 6,
    verseStart: 1,
    verseEnd: 4,
    testament: "nt",
    themes: ["familia", "relacionamentos", "servico"],
    editorialSummary:
      "À luz desse texto, filhos e pais são chamados a honra, obediência e educação sem provocação, no Senhor.",
    contextNote: "Códigos domésticos da carta aos efésios.",
    isPauline: true,
    denominationalNotes:
      "Aplicações familiares variam culturalmente; o núcleo de honra e cuidado permanece comum.",
  }),
  entry({
    id: "pv-22-6",
    book: "Provérbios",
    chapter: 22,
    verseStart: 6,
    testament: "ot",
    themes: ["familia", "proposito", "perseveranca"],
    editorialSummary:
      "Em síntese, instruir a criança no caminho adequado prepara um trajeto de vida.",
    contextNote: "Máxima educativa na tradição sapiencial.",
  }),
  entry({
    id: "1co-13-4-7",
    book: "1 Coríntios",
    chapter: 13,
    verseStart: 4,
    verseEnd: 7,
    testament: "nt",
    themes: ["relacionamentos", "amor_ao_proximo", "familia", "perseveranca"],
    editorialSummary:
      "A passagem ensina o perfil do amor: paciente, benigno, sem inveja nem arrogância, que tudo sofre e espera.",
    contextNote: "Hino ao amor no meio de conflitos da igreja de Corinto.",
    isPauline: true,
  }),
  entry({
    id: "mt-19-4-6",
    book: "Mateus",
    chapter: 19,
    verseStart: 4,
    verseEnd: 6,
    testament: "nt",
    themes: ["relacionamentos", "familia", "decisoes"],
    editorialSummary:
      "À luz desse texto, Jesus remete à criação: o que Deus uniu, o homem não separe.",
    contextNote: "Ensino sobre casamento em debate com fariseus.",
    isGospel: true,
    denominationalNotes:
      "Tradições divergem em disciplinas sacramentais e pastoral do casamento.",
  }),
  entry({
    id: "sl-68-6",
    book: "Salmos",
    chapter: 68,
    verseStart: 6,
    testament: "ot",
    themes: ["solidao", "familia", "esperanca"],
    editorialSummary:
      "Em síntese, Deus estabelece o solitário em família e tira o preso para a prosperidade.",
    contextNote: "Louvor ao Deus que restaura os marginalizados.",
  }),
  entry({
    id: "hb-13-5",
    book: "Hebreus",
    chapter: 13,
    verseStart: 5,
    testament: "nt",
    themes: ["solidao", "dinheiro", "fe", "ansiedade"],
    editorialSummary:
      "A passagem ensina contentamento e confiança: Deus não deixará nem abandonará.",
    contextNote: "Exortações finais de Hebreus sobre vida cristã.",
  }),
  entry({
    id: "mt-28-20",
    book: "Mateus",
    chapter: 28,
    verseStart: 20,
    testament: "nt",
    themes: ["solidao", "fe", "servico", "perseveranca"],
    editorialSummary:
      "À luz desse texto, Jesus promete estar com os discípulos todos os dias, até o fim dos tempos.",
    contextNote: "Grande Comissão — encerramento de Mateus.",
    isGospel: true,
  }),
  entry({
    id: "pv-3-5-6",
    book: "Provérbios",
    chapter: 3,
    verseStart: 5,
    verseEnd: 6,
    testament: "ot",
    themes: ["decisoes", "fe", "proposito", "mudanca"],
    editorialSummary:
      "Em síntese, confiar no Senhor de todo o coração e nele reconhecer os caminhos traz direção reta.",
    contextNote: "Conselho sapiencial clássico sobre confiança e orientação.",
  }),
  entry({
    id: "tg-1-5",
    book: "Tiago",
    chapter: 1,
    verseStart: 5,
    testament: "nt",
    themes: ["decisoes", "oracao", "fe"],
    editorialSummary:
      "A passagem ensina a pedir sabedoria a Deus, que dá liberalmente e sem censura.",
    contextNote: "Contexto de provas e perseverança na fé.",
  }),
  entry({
    id: "cl-3-23-24",
    book: "Colossenses",
    chapter: 3,
    verseStart: 23,
    verseEnd: 24,
    testament: "nt",
    themes: ["trabalho", "servico", "proposito"],
    editorialSummary:
      "Em síntese, o trabalho deve ser feito de coração, como para o Senhor, sabendo que a herança vem Dele.",
    contextNote: "Orientação a quem serve em relações assimétricas.",
    isPauline: true,
  }),
  entry({
    id: "pv-16-3",
    book: "Provérbios",
    chapter: 16,
    verseStart: 3,
    testament: "ot",
    themes: ["trabalho", "decisoes", "proposito"],
    editorialSummary:
      "A passagem ensina a entregar as obras ao Senhor para que os planos sejam estabelecidos.",
    contextNote: "Sabedoria sobre planejamento e dependência de Deus.",
  }),
  entry({
    id: "2ts-3-10-12",
    book: "2 Tessalonicenses",
    chapter: 3,
    verseStart: 10,
    verseEnd: 12,
    testament: "nt",
    themes: ["trabalho", "servico", "proposito"],
    editorialSummary:
      "À luz desse texto, quem não quer trabalhar não deve comer; e a comunidade é chamada a trabalhar com tranquilidade.",
    contextNote: "Correção pastoral contra ociosidade disruptiva.",
    isPauline: true,
  }),
  entry({
    id: "1tm-6-6-10",
    book: "1 Timóteo",
    chapter: 6,
    verseStart: 6,
    verseEnd: 10,
    testament: "nt",
    themes: ["dinheiro", "tentacao", "proposito", "gratidao"],
    editorialSummary:
      "Em síntese, a piedade com contentamento é grande ganho; o amor ao dinheiro é raiz de males.",
    contextNote: "Aviso a Timóteo sobre cobiça e falso ensino.",
    isPauline: true,
  }),
  entry({
    id: "pv-11-24-25",
    book: "Provérbios",
    chapter: 11,
    verseStart: 24,
    verseEnd: 25,
    testament: "ot",
    themes: ["dinheiro", "servico", "gratidao"],
    editorialSummary:
      "A passagem ensina a generosidade: quem disperse com justiça é enriquecido; a alma generosa prosperará.",
    contextNote: "Contraste sapiencial entre avareza e liberalidade.",
  }),
  entry({
    id: "lc-12-15",
    book: "Lucas",
    chapter: 12,
    verseStart: 15,
    testament: "nt",
    themes: ["dinheiro", "proposito", "tentacao"],
    editorialSummary:
      "À luz desse texto, a vida de alguém não consiste na abundância de bens.",
    contextNote: "Advertência antes da parábola do rico insensato.",
    isGospel: true,
  }),
  entry({
    id: "jr-29-11",
    book: "Jeremias",
    chapter: 29,
    verseStart: 11,
    testament: "ot",
    themes: ["proposito", "esperanca", "mudanca", "recomeco"],
    editorialSummary:
      "Em síntese, Deus declara planos de bem-estar e esperança futura para o povo exilado.",
    contextNote:
      "Carta aos exilados em Babilônia — promessa corporativa, não garantia individualista.",
    denominationalNotes:
      "Algumas tradições alertam contra leitura meramente individualista deste versículo.",
  }),
  entry({
    id: "ef-2-10",
    book: "Efésios",
    chapter: 2,
    verseStart: 10,
    testament: "nt",
    themes: ["proposito", "servico", "fe", "recomeco"],
    editorialSummary:
      "A passagem ensina que somos feitura de Deus, criados em Cristo para boas obras preparadas de antemão.",
    contextNote: "Após a salvação pela graça mediante a fé.",
    isPauline: true,
  }),
  entry({
    id: "rm-5-3-5",
    book: "Romanos",
    chapter: 5,
    verseStart: 3,
    verseEnd: 5,
    testament: "nt",
    themes: ["sofrimento", "esperanca", "perseveranca", "fe"],
    editorialSummary:
      "Em síntese, a tribulação produz perseverança, experiência e esperança que não decepciona.",
    contextNote: "Justificados pela fé e consolados no sofrimento.",
    isPauline: true,
  }),
  entry({
    id: "2co-1-3-4",
    book: "2 Coríntios",
    chapter: 1,
    verseStart: 3,
    verseEnd: 4,
    testament: "nt",
    themes: ["sofrimento", "luto", "servico", "esperanca"],
    editorialSummary:
      "À luz desse texto, Deus consola nas aflições para que possamos consolar outros com o mesmo consolo.",
    contextNote: "Abertura pastoral de 2 Coríntios.",
    isPauline: true,
  }),
  entry({
    id: "sl-46-1-2",
    book: "Salmos",
    chapter: 46,
    verseStart: 1,
    verseEnd: 2,
    testament: "ot",
    themes: ["sofrimento", "medo", "fe", "esperanca"],
    editorialSummary:
      "A passagem ensina que Deus é refúgio e fortaleza, socorro bem presente nas tribulações.",
    contextNote: "Salmo de confiança em meio a instabilidade.",
  }),
  entry({
    id: "mt-6-9-13",
    book: "Mateus",
    chapter: 6,
    verseStart: 9,
    verseEnd: 13,
    testament: "nt",
    themes: ["oracao", "perdao", "tentacao", "fe"],
    editorialSummary:
      "Em síntese, o Pai-Nosso modela a oração: santificar o nome de Deus, pedir o Reino, o pão, perdão e livramento.",
    contextNote: "Modelo de oração no Sermão do Monte.",
    isGospel: true,
    denominationalNotes:
      "A doxologia final varia em manuscritos e uso litúrgico entre tradições.",
  }),
  entry({
    id: "1ts-5-16-18",
    book: "1 Tessalonicenses",
    chapter: 5,
    verseStart: 16,
    verseEnd: 18,
    testament: "nt",
    themes: ["oracao", "gratidao", "fe", "perseveranca"],
    editorialSummary:
      "A passagem ensina a regozijar-se sempre, orar sem cessar e dar graças em todas as circunstâncias.",
    contextNote: "Exortações finais à igreja de Tessalônia.",
    isPauline: true,
  }),
  entry({
    id: "lc-18-1",
    book: "Lucas",
    chapter: 18,
    verseStart: 1,
    testament: "nt",
    themes: ["oracao", "perseveranca", "fe"],
    editorialSummary:
      "Em síntese, Jesus ensina a orar sempre e nunca desanimar.",
    contextNote: "Introdução à parábola da viúva e do juiz.",
    isGospel: true,
  }),
  entry({
    id: "hb-12-1-2",
    book: "Hebreus",
    chapter: 12,
    verseStart: 1,
    verseEnd: 2,
    testament: "nt",
    themes: ["perseveranca", "fe", "proposito", "sofrimento"],
    editorialSummary:
      "À luz desse texto, corremos com perseverança, fixando os olhos em Jesus, autor e consumador da fé.",
    contextNote: "Após a nuvem de testemunhas do capítulo 11.",
  }),
  entry({
    id: "gl-6-9",
    book: "Gálatas",
    chapter: 6,
    verseStart: 9,
    testament: "nt",
    themes: ["perseveranca", "servico", "trabalho"],
    editorialSummary:
      "A passagem ensina a não nos cansarmos de fazer o bem, pois a seu tempo colheremos.",
    contextNote: "Exortação comunitária no fechamento de Gálatas.",
    isPauline: true,
  }),
  entry({
    id: "mt-5-14-16",
    book: "Mateus",
    chapter: 5,
    verseStart: 14,
    verseEnd: 16,
    testament: "nt",
    themes: ["servico", "amor_ao_proximo", "proposito"],
    editorialSummary:
      "Em síntese, os discípulos são luz do mundo: as boas obras devem brilhar para glória do Pai.",
    contextNote: "Identidade pública do discípulo no Sermão do Monte.",
    isGospel: true,
  }),
  entry({
    id: "mt-25-35-40",
    book: "Mateus",
    chapter: 25,
    verseStart: 35,
    verseEnd: 40,
    testament: "nt",
    themes: ["servico", "amor_ao_proximo", "proposito"],
    editorialSummary:
      "A passagem ensina que servir ao faminto, estrangeiro, doente e preso é servir ao próprio Cristo.",
    contextNote: "Julgamento das nações — critério do cuidado concreto.",
    isGospel: true,
  }),
  entry({
    id: "lc-10-36-37",
    book: "Lucas",
    chapter: 10,
    verseStart: 36,
    verseEnd: 37,
    testament: "nt",
    themes: ["amor_ao_proximo", "servico", "conflitos"],
    editorialSummary:
      "À luz desse texto, o próximo é quem pratica misericórdia; Jesus ordena: vai e faze o mesmo.",
    contextNote: "Conclusão da parábola do bom samaritano.",
    isGospel: true,
  }),
  entry({
    id: "rm-12-18",
    book: "Romanos",
    chapter: 12,
    verseStart: 18,
    testament: "nt",
    themes: ["conflitos", "relacionamentos", "amor_ao_proximo"],
    editorialSummary:
      "Em síntese, quanto depender de vós, tende paz com todos.",
    contextNote: "Ética do corpo de Cristo após a exposição doutrinária.",
    isPauline: true,
  }),
  entry({
    id: "mt-5-23-24",
    book: "Mateus",
    chapter: 5,
    verseStart: 23,
    verseEnd: 24,
    testament: "nt",
    themes: ["conflitos", "perdao", "relacionamentos", "oracao"],
    editorialSummary:
      "A passagem ensina a priorizar a reconciliação antes de apresentar a oferta.",
    contextNote: "Ética do Sermão do Monte sobre ira e culto.",
    isGospel: true,
  }),
  entry({
    id: "1co-10-13",
    book: "1 Coríntios",
    chapter: 10,
    verseStart: 13,
    testament: "nt",
    themes: ["tentacao", "fe", "perseveranca"],
    editorialSummary:
      "À luz desse texto, nenhuma tentação é exclusiva; Deus é fiel e provê saída juntamente com a prova.",
    contextNote: "Advertência a Corinto sobre idolatria e soberba.",
    isPauline: true,
  }),
  entry({
    id: "mt-26-41",
    book: "Mateus",
    chapter: 26,
    verseStart: 41,
    testament: "nt",
    themes: ["tentacao", "oracao", "fe"],
    editorialSummary:
      "Em síntese, vigiai e orai, para não entrar em tentação: o espírito está pronto, a carne é fraca.",
    contextNote: "Getsêmani — alerta aos discípulos.",
    isGospel: true,
  }),
  entry({
    id: "sl-100-4-5",
    book: "Salmos",
    chapter: 100,
    verseStart: 4,
    verseEnd: 5,
    testament: "ot",
    themes: ["gratidao", "oracao", "fe"],
    editorialSummary:
      "A passagem ensina a entrar com ações de graças, reconhecendo a bondade e a fidelidade do Senhor.",
    contextNote: "Salmo de louvor comunitário.",
  }),
  entry({
    id: "sl-103-1-5",
    book: "Salmos",
    chapter: 103,
    verseStart: 1,
    verseEnd: 5,
    testament: "ot",
    themes: ["gratidao", "perdao", "recomeco"],
    editorialSummary:
      "Em síntese, a alma é chamada a bendizer o Senhor e não esquecer seus benefícios: perdão, cura e renovação.",
    contextNote: "Doxologia pessoal de memória grata.",
  }),
  entry({
    id: "rm-12-12",
    book: "Romanos",
    chapter: 12,
    verseStart: 12,
    testament: "nt",
    themes: ["perseveranca", "oracao", "esperanca"],
    editorialSummary:
      "A passagem ensina a alegrar-se na esperança, ser paciente na tribulação e perseverante na oração.",
    contextNote: "Marcas da vida cristã renovada.",
    isPauline: true,
  }),
  entry({
    id: "jo-15-4-5",
    book: "João",
    chapter: 15,
    verseStart: 4,
    verseEnd: 5,
    testament: "nt",
    themes: ["fe", "proposito", "perseveranca", "relacionamentos"],
    editorialSummary:
      "À luz desse texto, permanecer em Cristo é condição para dar fruto; sem Ele nada podemos fazer.",
    contextNote: "Alegoria da videira verdadeira.",
    isGospel: true,
  }),
  entry({
    id: "lc-1-46-49",
    book: "Lucas",
    chapter: 1,
    verseStart: 46,
    verseEnd: 49,
    testament: "nt",
    themes: ["gratidao", "fe", "oracao"],
    editorialSummary:
      "Em síntese, Maria magnifica o Senhor e se alegra em Deus Salvador, reconhecendo as grandes coisas feitas a ela.",
    contextNote:
      "Magnificat — cântico bíblico de Maria. Uso devocional mariano adicional depende da tradição.",
    isGospel: true,
    requiresSaintsContent: true,
    denominationalNotes:
      "O texto é bíblico; práticas de intercessão e devoção a Maria são próprias de tradições que as permitem e devem ser omitidas para perfil evangélico.",
  }),
];
